//Profile Types of Action
export const GET_PROFILE_PENDING = "GET_PROFILE_PENDING";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAILED = "GET_PROFILE_FAILED";

//Repositories Types of Action
export const GET_REPOSITORIES_PENDING = "GET_REPOSITORIES_PENDING";
export const GET_REPOSITORIES_SUCCESS = "GET_REPOSITORIES_SUCCESS";
export const GET_REPOSITORIES_FAILED = "GET_REPOSITORIES_FAILED";
